os: Visual Studio 2015

environment:
  matrix:
    - target: x86_64-pc-windows-msvc
    #- target: i686-pc-windows-msvc
    #- target: x86_64-pc-windows-gnu
    #- target: i686-pc-windows-gnu

install:
  - ps: |
      Function test() {
        param($target)
        /usr/bin/false
      }

build: false

test_script:
  - ps: |
      test
