os: Visual Studio 2015

environment:
  matrix:
    - target: x86_64-pc-windows-msvc
    #- target: i686-pc-windows-msvc
    #- target: x86_64-pc-windows-gnu
    #- target: i686-pc-windows-gnu

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-host %target% --default-toolchain stable
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - ps: |
      Function test() {
        param($target)
        rustup run "$target" cargo test
        rustup run "$target" cargo test --release
      }

build: false

test_script:
  - test %target%
