os: Visual Studio 2015

environment:
  matrix:
    - target: x86_64-pc-windows-msvc
    #- target: i686-pc-windows-msvc
    #- target: x86_64-pc-windows-gnu
    #- target: i686-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-host %target% --default-toolchain stable
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup install beta
  - ps: |
      Function testFN() {
        param([string]$target)
        rustup run "$target" cargo test 2> $null
        if ($? -ne $true) {
          echo "Rust error; Exit code $LASTEXITCODE"
          exit $LASTEXITCODE
        }
        rustup run "$target" cargo test --release
        if ($? -ne $true) {
          echo "Rust error; Exit code $LASTEXITCODE"
          exit $LASTEXITCODE
        }
      }

build: false

test_script:
  - ps: testFN "stable"
  - ps: testFN "beta"
