os: Visual Studio 2015

environment:
  matrix:
    - target: x86_64-pc-windows-msvc
    #- target: i686-pc-windows-msvc
    #- target: x86_64-pc-windows-gnu
    #- target: i686-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-host %target% --default-toolchain stable
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup install beta
  - ps: |
      Function testFN() {
        param([string]$target)
        echo "Executing _rustup run $target cargo test $args_"
        cmd /c "rustup run $target cargo test $args 2>&1"
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
        echo "Executing _rustup run $target cargo test --release $args_"
        cmd /c "rustup run $target cargo test --release $args 2>&1"
        if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
      }

build: false

test_script:
  - ps: testFN "stable" --no-default-features
  - ps: testFN "beta" --features error
