os: Visual Studio 2015

environment:
  matrix:
    - target: x86_64-pc-windows-msvc
    #- target: i686-pc-windows-msvc
    #- target: x86_64-pc-windows-gnu
    #- target: i686-pc-windows-gnu

install:
  - ps: |
      Write-Host "Hello from Powershell!"
      Function test() {
        Write-Host "Hello2"
      }
      test

build: false

test_script:
  - ps: |
      test
