[package]
name = "t"
version = "0.1.0"
authors = ["Draphar <draphar-code@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = []
error = []